eutils_base_url : "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
medical_topics : [
  "Diabetes", 
  "Hypertension", 
  "Arthritis"
]
retmax_per_topic : 20
raw_ingested_data_file : "pubmed_articles_data.json"